apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - rolearn: arn:aws:iam::628175736197:user/github-ci
      username: github-ci
      groups:
        - system:masters
